# Booth Preferences
This notebook explores the both preference data supplied by the Australian Electoral Commission (AEC)

In [1]:
import pandas as pd

## Read in booth data

In [11]:
booth_info_loc = 'data/20190518/GeneralPollingPlacesDownload-24310.csv'

try:
    booths = pd.read_csv(booth_info_loc,
                         skiprows=1)
except IOError:
    booths = pd.read_csv('https://results.aec.gov.au/24310/Website/Downloads/GeneralPollingPlacesDownload-24310.csv')
    booths.to_csv(booth_info_loc)
    booths = pd.read_csv(booth_info_loc,
                         skiprows=1)

booths.head()

,State,DivisionID,DivisionNm,PollingPlaceID,PollingPlaceTypeID,PollingPlaceNm,PremisesNm,PremisesAddress1,PremisesAddress2,PremisesAddress3,PremisesSuburb,PremisesStateAb,PremisesPostCode,Latitude,Longitude
0,ACT,318,Bean,93925,5,Belconnen BEAN PPVC,Belconnen Community Centre,26 Chandler St,NaN,NaN,BELCONNEN,ACT,2900.0,-35.238930,149.069655
1,ACT,318,Bean,93927,5,BLV Bean PPVC,BLV Canberra,50 Marcus Clarke St,NaN,NaN,CANBERRA CITY,ACT,2601.0,-35.277334,149.126869
2,ACT,318,Bean,11877,1,Bonython,Bonython Primary School,64 Hurtle Ave,NaN,NaN,BONYTHON,ACT,2905.0,-35.431800,149.083000
3,ACT,318,Bean,11452,1,Calwell,Calwell High School,111 Casey Cres,NaN,NaN,CALWELL,ACT,2905.0,-35.440670,149.117600
4,ACT,318,Bean,8761,1,Chapman,Chapman Primary School,46-50 Perry Dr,NaN,NaN,CHAPMAN,ACT,2611.0,-35.356400,149.042000

In [2]:
act_first_pref_loc = 'data/20190518/HouseStateFirstPrefsByPollingPlaceDownload-24310-ACT.csv'

try:
    act_first_pref = pd.read_csv(act_first_pref_loc,
                         skiprows=1)
except IOError:
    act_first_pref = pd.read_csv('https://results.aec.gov.au/24310/Website/Downloads/GeneralPollingPlacesDownload-24310.csv')
    act_first_pref.to_csv(act_first_pref_loc)
    act_first_pref = pd.read_csv(act_first_pref_loc,
                         skiprows=1)

act_first_pref.head()

,StateAb,DivisionID,DivisionNm,PollingPlaceID,PollingPlace,CandidateID,Surname,GivenNm,BallotPosition,Elected,HistoricElected,PartyAb,PartyNm,OrdinaryVotes,Swing
0,ACT,318,Bean,93925,Belconnen BEAN PPVC,33426,FAULKNER,Therese,1,N,N,AUP,Australian Progressives,22,3.12
1,ACT,318,Bean,93925,Belconnen BEAN PPVC,32130,CHRISTIE,Jamie,2,N,N,IND,Independent,43,6.09
2,ACT,318,Bean,93925,Belconnen BEAN PPVC,33391,RUSHTON,Ben,3,N,N,GAP,The Great Australian Party,12,1.70
3,ACT,318,Bean,93925,Belconnen BEAN PPVC,32921,DONNELLY,Matt,4,N,N,LDP,Liberal Democrats,23,3.26
4,ACT,318,Bean,93925,Belconnen BEAN PPVC,32261,HANLEY,Tony,5,N,N,UAPP,United Australia Party,18,2.55

In [3]:
act_first_pref.describe()

,DivisionID,PollingPlaceID,CandidateID,BallotPosition,OrdinaryVotes,Swing
count,1059.000000,1059.000000,1059.000000,1059.000000,1059.000000,1059.000000
mean,195.303116,46424.749764,28383.264400,138.206799,230.325779,1.063664
std,107.367299,36863.666470,10832.386413,340.275727,534.887449,5.651046
min,101.000000,8761.000000,999.000000,1.000000,0.000000,-34.730000
25%,101.000000,8806.000000,32253.000000,2.000000,18.000000,-0.700000
50%,102.000000,32705.000000,32405.000000,4.000000,54.000000,1.600000
75%,318.000000,83857.000000,32888.000000,6.000000,253.500000,3.195000
max,318.000000,97559.000000,33426.000000,999.000000,6623.000000,39.030000

Most of these fields don't make much sense to do a descrive: DividionID, PollingPlaceID, CandidateID are all categorical. BallotPosition having a max of 999 seems wrong though. What is happening there?

In [4]:
act_first_pref[act_first_pref['BallotPosition']==999]

,StateAb,DivisionID,DivisionNm,PollingPlaceID,PollingPlace,CandidateID,Surname,GivenNm,BallotPosition,Elected,HistoricElected,PartyAb,PartyNm,OrdinaryVotes,Swing
8,ACT,318,Bean,93925,Belconnen BEAN PPVC,999,Informal,Informal,999,N,N,NaN,Informal,43,3.73
17,ACT,318,Bean,93927,BLV Bean PPVC,999,Informal,Informal,999,N,N,NaN,Informal,0,-2.94
26,ACT,318,Bean,11877,Bonython,999,Informal,Informal,999,N,N,NaN,Informal,94,3.82
35,ACT,318,Bean,11452,Calwell,999,Informal,Informal,999,N,N,NaN,Informal,108,1.44
44,ACT,318,Bean,8761,Chapman,999,Informal,Informal,999,N,N,NaN,Informal,62,0.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1034,ACT,102,Fenner,32467,Special Hospital Team 1,999,Informal,Informal,999,N,N,NaN,Informal,9,1.20
1040,ACT,102,Fenner,97559,Taylor,999,Informal,Informal,999,N,N,NaN,Informal,40,-0.44
1046,ACT,102,Fenner,64585,Tuggeranong FENNER PPVC,999,Informal,Informal,999,N,N,NaN,Informal,18,-1.26
1052,ACT,102,Fenner,94016,Weetangera (Fenner),999,Informal,Informal,999,N,N,NaN,Informal,7,0.68
1058,ACT,102,Fenner,64584,Woden FENNER PPVC,999,Informal,Informal,999,N,N,NaN,Informal,33,-1.07

It is the informal votes, who didn't have a position on the ballet to report. I am going to keep them in as it may be an interesting datapoint for later

In [6]:
act_first_pref[act_first_pref['OrdinaryVotes']==0]['PartyNm'].unique()

array(['The Great Australian Party', 'United Australia Party', 'Informal',
       'Liberal Democrats', 'Australian Progressives', 'Independent',
       'The Greens', 'Australian Labor Party', 'Liberal'], dtype=object)

Interesting that there are some booths where even the major parties received no votes

In [7]:
act_first_pref[(act_first_pref['OrdinaryVotes']==0) & (act_first_pref['PartyNm']=='Australian Labor Party')]

,StateAb,DivisionID,DivisionNm,PollingPlaceID,PollingPlace,CandidateID,Surname,GivenNm,BallotPosition,Elected,HistoricElected,PartyAb,PartyNm,OrdinaryVotes,Swing
930,ACT,102,Fenner,83863,Hall PPVC,32258,LEIGH,Andrew,4,Y,Y,ALP,Australian Labor Party,0,0.0

In [8]:
act_first_pref[act_first_pref['PollingPlace']=='Hall PPVC']

,StateAb,DivisionID,DivisionNm,PollingPlaceID,PollingPlace,CandidateID,Surname,GivenNm,BallotPosition,Elected,HistoricElected,PartyAb,PartyNm,OrdinaryVotes,Swing
927,ACT,102,Fenner,83863,Hall PPVC,32270,HODGSON,Glen J,1,N,N,UAPP,United Australia Party,0,0.0
928,ACT,102,Fenner,83863,Hall PPVC,32888,RATLHAGANE,Kagiso,2,N,N,AUP,Australian Progressives,0,0.0
929,ACT,102,Fenner,83863,Hall PPVC,32406,BRADDOCK,Andrew,3,N,N,GRN,The Greens,0,0.0
930,ACT,102,Fenner,83863,Hall PPVC,32258,LEIGH,Andrew,4,Y,Y,ALP,Australian Labor Party,0,0.0
931,ACT,102,Fenner,83863,Hall PPVC,32861,CASTLEY,Leanne,5,N,N,LP,Liberal,0,0.0
932,ACT,102,Fenner,83863,Hall PPVC,999,Informal,Informal,999,N,N,NaN,Informal,0,0.0

So this polling place seems to be closed on the day. Check what further information we have on this booth:

In [13]:
booths[booths['PollingPlaceID']==83863]

,State,DivisionID,DivisionNm,PollingPlaceID,PollingPlaceTypeID,PollingPlaceNm,PremisesNm,PremisesAddress1,PremisesAddress2,PremisesAddress3,PremisesSuburb,PremisesStateAb,PremisesPostCode,Latitude,Longitude
121,ACT,102,Fenner,83863,5,Hall PPVC,Hall Pavillion,21 Gladstone St,NaN,NaN,HALL,ACT,2618.0,NaN,NaN

It is PollingPlaceTypeId=5, I don't know what that means at this stage. When we were looking at booths in `explore_booths.ipynb` we concluded to just consider `PollingPlaceTypeID=1` as they are moslty likely to represent a voters' local both

In [20]:
local_booths_ids = booths.loc[booths['PollingPlaceTypeID']==1, 'PollingPlaceID']
act_first_pref = act_first_pref[act_first_pref['PollingPlaceID'].isin(local_booths_ids)]
act_first_pref

,StateAb,DivisionID,DivisionNm,PollingPlaceID,PollingPlace,CandidateID,Surname,GivenNm,BallotPosition,Elected,HistoricElected,PartyAb,PartyNm,OrdinaryVotes,Swing
18,ACT,318,Bean,11877,Bonython,33426,FAULKNER,Therese,1,N,N,AUP,Australian Progressives,42,3.16
19,ACT,318,Bean,11877,Bonython,32130,CHRISTIE,Jamie,2,N,N,IND,Independent,99,7.44
20,ACT,318,Bean,11877,Bonython,33391,RUSHTON,Ben,3,N,N,GAP,The Great Australian Party,13,0.98
21,ACT,318,Bean,11877,Bonython,32921,DONNELLY,Matt,4,N,N,LDP,Liberal Democrats,31,2.33
22,ACT,318,Bean,11877,Bonython,32261,HANLEY,Tony,5,N,N,UAPP,United Australia Party,25,1.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048,ACT,102,Fenner,94016,Weetangera (Fenner),32888,RATLHAGANE,Kagiso,2,N,N,AUP,Australian Progressives,5,2.14
1049,ACT,102,Fenner,94016,Weetangera (Fenner),32406,BRADDOCK,Andrew,3,N,N,GRN,The Greens,40,2.60
1050,ACT,102,Fenner,94016,Weetangera (Fenner),32258,LEIGH,Andrew,4,Y,Y,ALP,Australian Labor Party,119,3.96
1051,ACT,102,Fenner,94016,Weetangera (Fenner),32861,CASTLEY,Leanne,5,N,N,LP,Liberal,53,-9.80
1052,ACT,102,Fenner,94016,Weetangera (Fenner),999,Informal,Informal,999,N,N,NaN,Informal,7,0.68

In [21]:
act_first_pref.describe()

,DivisionID,PollingPlaceID,CandidateID,BallotPosition,OrdinaryVotes,Swing
count,764.000000,764.000000,764.000000,764.000000,764.000000,764.000000
mean,198.397906,36131.345550,28391.994764,138.000000,195.108639,0.876270
std,107.741396,35917.981052,10827.912186,340.104382,254.718234,4.467906
min,101.000000,8761.000000,999.000000,1.000000,0.000000,-15.980000
25%,101.000000,8788.000000,32253.000000,2.000000,30.000000,-0.740000
50%,102.000000,8834.000000,32405.000000,4.000000,65.000000,1.580000
75%,318.000000,83835.000000,32888.000000,6.000000,285.250000,3.112500
max,318.000000,97559.000000,33426.000000,999.000000,1226.000000,14.750000

Still some booths with zero votes for a candidate

In [24]:
act_first_pref[act_first_pref['OrdinaryVotes']==0]['PartyNm'].unique()

array(['United Australia Party', 'The Great Australian Party'],
      dtype=object)

These are both smaller minor parties, it is not suprising that there are booth with no first preference votes for these candidates.

The next thing I want to explore is how often these a candidate is elected based on first preferences. This is imoprtant as since I don't have access to the preferences flows, and I want to see how often it comes into effect

In [28]:
act_first_pref.groupby(['DivisionNm', 'PartyNm', 'Elected'])['OrdinaryVotes'].sum().sort_values(ascending=False)

DivisionNm  PartyNm                     Elected
Fenner      Australian Labor Party      Y          20835
Bean        Australian Labor Party      Y          20167
Canberra    Australian Labor Party      Y          19381
Bean        Liberal                     N          14981
Fenner      Liberal                     N          14626
Canberra    The Greens                  N          12011
            Liberal                     N          11707
Fenner      The Greens                  N           7269
Bean        The Greens                  N           7149
            Independent                 N           4583
            Informal                    N           2866
Canberra    Independent                 N           2133
Fenner      United Australia Party      N           1678
Bean        Australian Progressives     N           1579
Fenner      Informal                    N           1411
Bean        Liberal Democrats           N           1334
            United Australia Party      N           1209
Canberra    Australian Progressives     N           1040
Fenner      Australian Progressives     N            983
Canberra    Informal                    N            960
            United Australia Party      N            641
Bean        The Great Australian Party  N            520
Name: OrdinaryVotes, dtype: int64

So at least in the ACT all three seats got passed on first preferences. This is definitely not the case for all divisiosn, so will need to re-examine when it comes to the whole country. Perhaps if more than 75% seats are passed on first preferences I won't stress so much about it

booths

In [29]:
booths[booths['Divis']]

,State,DivisionID,DivisionNm,PollingPlaceID,PollingPlaceTypeID,PollingPlaceNm,PremisesNm,PremisesAddress1,PremisesAddress2,PremisesAddress3,PremisesSuburb,PremisesStateAb,PremisesPostCode,Latitude,Longitude
0,ACT,318,Bean,93925,5,Belconnen BEAN PPVC,Belconnen Community Centre,26 Chandler St,NaN,NaN,BELCONNEN,ACT,2900.0,-35.238930,149.069655
1,ACT,318,Bean,93927,5,BLV Bean PPVC,BLV Canberra,50 Marcus Clarke St,NaN,NaN,CANBERRA CITY,ACT,2601.0,-35.277334,149.126869
2,ACT,318,Bean,11877,1,Bonython,Bonython Primary School,64 Hurtle Ave,NaN,NaN,BONYTHON,ACT,2905.0,-35.431800,149.083000
3,ACT,318,Bean,11452,1,Calwell,Calwell High School,111 Casey Cres,NaN,NaN,CALWELL,ACT,2905.0,-35.440670,149.117600
4,ACT,318,Bean,8761,1,Chapman,Chapman Primary School,46-50 Perry Dr,NaN,NaN,CHAPMAN,ACT,2611.0,-35.356400,149.042000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8870,WA,248,Tangney,8283,1,Willetton,Willetton Primary School,14 Woodpecker Ave,NaN,NaN,WILLETTON,WA,6155.0,-32.048500,115.882000
8871,WA,248,Tangney,8284,1,Willetton East,Rostrata Primary School,30 Rostrata Ave,NaN,NaN,WILLETTON,WA,6155.0,-32.051100,115.899000
8872,WA,248,Tangney,11907,1,Willetton North,Herald Avenue Senior Citizens Centre,2 Herald Ave,NaN,NaN,WILLETTON,WA,6155.0,-32.039100,115.889000
8873,WA,248,Tangney,8285,1,Willetton South,Willetton Senior High School,120-124 Pinetree Gully Rd,NaN,NaN,WILLETTON,WA,6155.0,-32.062300,115.880000
8874,WA,248,Tangney,11635,1,Winthrop,Winthrop Primary School,70-80 Jackson Ave,NaN,NaN,WINTHROP,WA,6150.0,-32.054100,115.833000